apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-world.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "hello-world.fullname" . }}
    spec:
      containers:
        - name: hello-world
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hello-world.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
